myportfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sixg.urls')),
]

sixg/urls.py
from django.urls import path, include
from .views import index, services
from .views import *
from . import views
from django.contrib import admin

app_name = "sixg"

urlpatterns = [
    path('', index, name='index'),
    path('our-work/', our_work, name='our-work'),
    path('our-work-single/', our_work_single, name='our-work-single'),
    path('about/', about_us, name='about-us'),
    path('services/', services, name='services'),
    path('services-single/', services_single, name='services-single'),
    path('blog/', blog, name='blog'),
    path('contact/', views.contact, name='contact'),

]

sixg/models.py
from django.db import models


# Create your models here.

sixg/forms.py
from django import forms

class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea,
                              max_length=2000)

sixg/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
# Create your views here.

def index(request):
    return render(request, 'sixg/main.html')

def our_work(request):
    return render(request, 'sixg/our-work.html')

def our_work_single(request):
    return render(request, 'sixg/app-single.html')

def about_us(request):
    return render(request, 'sixg/about-us.html')

def services(request):
    return render(request, 'sixg/services.html')

def services_single(request):
    return render(request, 'sixg/services-single.html')

def blog(request):
    return render(request, 'sixg/blog.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject ='пробное сообщение'
            body = {
                'first_name': form.cleaned_data['first_name'],
                'email':form.cleaned_data['email_address'],
                'message':form.cleaned_data['message']
            }
            message = '\n'.join(body.values())
            try:
                send_mail(subject,message,
                          'admin@example.com',
                          ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Найден некорректный заголовок')
            return redirect("sixg:index")

    form = ContactForm
    return render(request, 'sixg/contact.html', {'form':form})

sixg/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>6g - создание сайтов и приложений</title>
	<meta name="description" content="sixg.ru - создание сайтов и приложений." />
	<meta name="keywords" content="sixg.ru - создание сайтов и приложений, mobile app, agency, development, html, template, tempload" />
	<meta name="author" content="tempload"/>

	<!-- Favicon -->
	<link rel="icon" type="image/png" href="{% static 'sixg/images/favicon.png' %}" />

	<!-- Bootstrap & Plugins CSS -->
	<link href="{% static 'sixg/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'sixg/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'sixg/css/owl.carousel.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'sixg/css/owl.theme.default.min.css' %}" rel="stylesheet" type="text/css">

	<!-- Custom CSS -->
	<link href="{% static 'sixg/css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="home-body">

	<!-- ***** Preloader Start ***** -->
	<div class="loader-wrapper">
		<div class="loader">
			<div class="diamond"></div>
			<div class="diamond"></div>
			<div class="diamond"></div>
		</div>
	</div>
	<!-- ***** Preloader End ***** -->

	<!-- ***** Header Area Start ***** -->
	<header class="header-area light-header">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<nav class="main-nav">
						<!-- ***** Logo Start ***** -->
						<a href="{% url 'sixg:index' %}" class="logo">
							<p class="light-logo" alt="sixg" ><strong><span style="font-size:36px" p><span style="font-family:Tahoma,Geneva,sans-serif"><span style="color:#33ccff">6</span><span style="color:#e74c3c" >G</span></span></span></strong></p>
                            <p class="dark-logo" alt="sixg" style="vertical-align: top"><strong><span style="font-size:36px" ><span style="font-family:Tahoma,Geneva,sans-serif"><span style="color:#33ccff">6</span><span style="color:#e74c3c" >G</span></span></span></strong></p>

						</a>
						<!-- ***** Logo End ***** -->


						<!-- ***** Menu Start ***** -->
						<ul class="nav">
								<li><a href="{% url 'sixg:index' %}">Главная</a></li>
							<li class="submenu">
								<a href="javascript:;">Наши работы</a>
								<ul>
									<li><a href="#">в разработке</a></li>
									<li><a href="#">в разработке</a></li>
								</ul>
							</li>
							<li class="submenu">
								<a href="javascript:;">Дополнительно</a>
								<ul>
									<li><a href="{% url 'sixg:about-us' %}">О нас</a></li>
									<li><a href="{% url 'sixg:services' %}">Услуги</a></li>
									<li><a href="#">в разработке</a></li>
								</ul>
							</li>
							<li class="submenu">
								<a href="javascript:;">Блог</a>
								<ul>
									<li><a href="#">в разработке</a></li>
									<li><a href="#">в разработке</a></li>
								</ul>
							</li>
							<li><a href="{% url 'sixg:contact' %}">Контакты</a></li>
						</ul>
						<a class="menu-trigger">
							<span>Menu</span>
						</a>
						<!-- ***** Menu End ***** -->
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- ***** Header Area End ***** -->

     {% block content %}

                {% endblock %}





	<!-- ***** Footer Start ***** -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-12 col-sm-12">
					<img src="{% static 'sixg/images/blue-logo-white.sv' %}" class="logo" alt="">
					<div class="text">Мы молодая компания начинающих разработчиков, трудимся на благо клиентов, и готовы браться за проекты любой сложности.</div>
				</div>
				<div class="col-lg-2 col-md-4 col-sm-6 col-6">
					<h5>Дополнительно</h5>
					<ul class="footer-nav">
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Наши работы</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>О нас</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Services</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Блог</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Контакты</span></a></li>
					</ul>
				</div>
				<div class="col-lg-2 col-md-4 col-sm-6 col-6">
					<h5>Последние проекты</h5>
					<ul class="footer-nav">
						<li><a href="tokenote.ru"><i class="fa fa-angle-right"></i><span>Сайт криптовалют</span></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-4 col-sm-12">
					<h5>Контакты</h5>
					<div class="address">
						<p>Пр.Ленина д.34<br>Чебоксары, Чувашская Республика</p>
						<p>Телефон: +7(917)676-76-59</p>
						<p><span>E-Mail:</span><a href="#">sales@sixg.ru</a></p>
						<ul class="social">
							<li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
							<li><a href="#"><i class="fa fa-github-square"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<p class="copyright">© 2022 Sixg. Студия по разработке сайтов и приложений.</p>
				</div>
			</div>
		</div>
	</footer>
	<!-- ***** Footer Start ***** -->



	<!-- jQuery -->
	<script src="{% static 'sixg/js/jquery-2.1.0.min.js' %}"></script>

	<!-- Bootstrap -->
	<script src="{% static 'sixg/js/popper.js' %}"></script>
	<script src="{% static 'sixg/js/bootstrap.min.js' %}"></script>

	<!-- Plugins -->
	<script src="{% static 'sixg/js/scrollreveal.min.js' %}"></script>
	<script src="{% static 'sixg/js/parallax.min.js' %}"></script>
	<script src="{% static 'sixg/js/waypoints.min.js' %}"></script>
	<script src="{% static 'sixg/js/jquery.counterup.min.js' %}"></script>
	<script src="{% static 'sixg/js/imgfix.min.js' %}"></script>
	<script src="{% static 'sixg/js/owl.carousel.min.js' %}"></script>

	<!-- Global Init -->
	<script src="{% static 'sixg/js/custom.js' %}"></script>
</body>
</html>

sixg/templates/layout/base_all.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>6g - создание сайтов и приложений</title>
	<meta name="description" content="sixg.ru - создание сайтов и приложений." />
	<meta name="keywords" content="sixg.ru - создание сайтов и приложений, mobile app, agency, development, html, template, tempload" />
	<meta name="author" content="tempload"/>

	<!-- Favicon -->
	<link rel="icon" type="image/png" href="{% static 'sixg/images/favicon.png' %}" />

	<!-- Bootstrap & Plugins CSS -->
	<link href="{% static 'sixg/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'sixg/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'sixg/css/magnific-popup.css' %}" rel="stylesheet" type="text/css">

	<!-- Custom CSS -->
	<link href="{% static 'sixg/css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

	<!-- ***** Preloader Start ***** -->
	<div class="loader-wrapper">
		<div class="loader">
			<div class="diamond"></div>
			<div class="diamond"></div>
			<div class="diamond"></div>
		</div>
	</div>
	<!-- ***** Preloader End ***** -->

	<!-- ***** Header Area Start ***** -->
	<header class="header-area header-white header-sticky">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<nav class="main-nav">
						<!-- ***** Logo Start ***** -->
						<a href="{% url 'sixg:index' %}" class="logo">
							<p class="light-logo" alt="sixg" ><strong><span style="font-size:36px" p><span style="font-family:Tahoma,Geneva,sans-serif"><span style="color:#33ccff">6</span><span style="color:#e74c3c" >G</span></span></span></strong></p>
                            <p class="dark-logo" alt="sixg" style="vertical-align: top"><strong><span style="font-size:36px" ><span style="font-family:Tahoma,Geneva,sans-serif"><span style="color:#33ccff">6</span><span style="color:#e74c3c" >G</span></span></span></strong></p>
						</a>
						<!-- ***** Logo End ***** -->

						<!-- ***** Menu Start ***** -->
					<ul class="nav">
								<li><a href="{% url 'sixg:index' %}">Главная</a></li>
							<li class="submenu">
								<a href="javascript:;">Наши работы</a>
								<ul>
									<li><a href="#">в разработке</a></li>
									<li><a href="#">в разработке</a></li>
								</ul>
							</li>
							<li class="submenu">
								<a href="javascript:;">Дополнительно</a>
								<ul>
									<li><a href="{% url 'sixg:about-us' %}">О нас</a></li>
									<li><a href="{% url 'sixg:services' %}">Услуги</a></li>
									<li><a href="#">в разработке</a></li>
								</ul>
							</li>
							<li class="submenu">
								<a href="javascript:;">Блог</a>
								<ul>
									<li><a href="#">в разработке</a></li>
									<li><a href="#">в разработке</a></li>
								</ul>
							</li>
							<li><a href="{% url 'sixg:contact' %}">Контакты</a></li>
						</ul>
						<a class="menu-trigger">
							<span>Menu</span>
						</a>
						<!-- ***** Menu End ***** -->
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- ***** Header Area End ***** -->
<!-- ***** индивидуальный блок для каждой страницы ***** -->
                {% block content %}

                {% endblock %}
<!-- ***** Конец индивидуальный блок для каждой страницы ***** -->


	<!-- ***** Footer Start ***** -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-12 col-sm-12">
					<img src="{% static 'sixg/images/blue-logo-white.sv' %}" class="logo" alt="">
					<div class="text">Мы молодая компания начинающих разработчиков, трудимся на благо клиентов, и готовы браться за проекты любой сложности.</div>
				</div>
				<div class="col-lg-2 col-md-4 col-sm-6 col-6">
					<h5>Дополнительно</h5>
					<ul class="footer-nav">
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Наши работы</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>О нас</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Услуги</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Блог</span></a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i><span>Контакты</span></a></li>
					</ul>
				</div>
				<div class="col-lg-2 col-md-4 col-sm-6 col-6">
					<h5>Последние проекты</h5>
					<ul class="footer-nav">
						<li><a href="tokenote.ru"><i class="fa fa-angle-right"></i><span>Сайт криптовалют</span></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-4 col-sm-12">
					<h5>Контакты</h5>
					<div class="address">
						<p>Пр.Ленина д.34<br>Чебоксары, Чувашская Республика</p>
						<p>Телефон: +7(917)676-76-59</p>
						<p><span>E-Mail:</span><a href="#">sales@sixg.ru</a></p>
						<ul class="social">
							<li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
							<li><a href="#"><i class="fa fa-github-square"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<p class="copyright">© 2022 Sixg. Студия по разработке сайтов и приложений.</p>
				</div>
			</div>
		</div>
	</footer>
	<!-- ***** Footer Start ***** -->



<!-- jQuery -->
	<script src="{% static 'sixg/js/jquery-2.1.0.min.js' %}"></script>

	<!-- Bootstrap -->
	<script src="{% static 'sixg/js/popper.js' %}"></script>
	<script src="{% static 'sixg/js/bootstrap.min.js' %}"></script>

	<!-- Plugins -->
	<script src="{% static 'sixg/js/scrollreveal.min.js' %}"></script>
	<script src="{% static 'sixg/js/parallax.min.js' %}"></script>
	<script src="{% static 'sixg/js/waypoints.min.js' %}"></script>
	<script src="{% static 'sixg/js/jquery.counterup.min.js' %}"></script>
	<script src="{% static 'sixg/js/imgfix.min.js' %}"></script>
	<script src="{% static 'sixg/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'sixg/js/jquery.magnific-popup.min.js' %}"></script>

	<!-- Global Init -->
	<script src="{% static 'sixg/js/custom.js' %}"></script>
</body>
</html>

sixg/templates/sixg/about-us.html
{% extends "layout/base_all.html" %}
{% load static %}

{% block content %}

	<section class="page">
		<!-- ***** Page Top Start ***** -->
		<div class="cover" data-image="assets/images/photos/parallax.jpg">
			<div class="page-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<h1>О нас</h1>
						</div>
						<div class="col-lg-12 text-center">
							<ol class="breadcrumb">
								<li><a href="{% url 'sixg:index' %}">Главная</a></li>
								<li class="active">О нас</li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ***** Page Top End ***** -->

		<!-- ***** Page Content Start ***** -->
		<div class="page-bottom pbottom-80">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="about-content">
							<div class="col-lg-12">
								<div class="about">
									<div class="about-image">
										<img src="{% static 'sixg/images/photos/about/1.jpg' %}" alt="">
									</div>
									<div class="about-text">
										<h2>Мы ответсвенные разработчики</h2>
										<p>Мы тщательно планируем все этапы ведения вашего проекта.</p>
										<p>Мы практикуем креативный подход к проектам.</p>
									</div>
								</div>
								<div class="about left mbottom-20">
									<div class="about-image">
										<img src="{% static 'sixg/images/photos/about/2.jpg' %}" alt="">
									</div>
									<div class="about-text">
										<h2>Выполним проект в согласованные сроки</h2>
										<p>Мы обсуждаем с вами техническое задание и даем реальные сроки выполнения которые должны устроить и вас и нас</p>
										<p>Всегда готовы добавить новый функционал.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ***** Page Content End ***** -->
	</section>

	<!-- ***** Parallax Start ***** -->
	<section class="parallax">
		<div class="parallax-content">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="info">
							<p>Мы разрабатываем и создаем дизайн <span>ваших проектов</span> которые помогут вам вести бизнес.</p>
							<a class="btn-white-line" href="{% url 'sixg:contact' %}">Свяжитесь с нами</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- ***** Parallax End ***** -->

	<!-- ***** Our Team Start ***** -->
	<section class="section pbottom-80">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="center-heading">
						<h2 class="section-title">Наша команда</h2>
					</div>
				</div>
				<div class="offset-lg-3 col-lg-6">
					<div class="center-text">
						<p>В разработке</p>
					</div>					
				</div>
			</div>
			{% comment %}<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
					<div class="team-item">
						<div class="header">
							<div class="img">
								<img src="{% static 'sixg/images/photos/team/1.jpg' %}" alt="">
							</div>
							<div class="info">
								<strong>Fletch Skinner</strong>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-github"></i></a></li>
								</ul>
							</div>
						</div>
						<span>Product Strategist</span>
						<div class="body">
							Proin arcu ligula, malesuada id tincidunt laoreet, facilisis at justo. Sed at lorem.
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
					<div class="team-item active">
						<div class="header">
							<div class="img">
								<img src="{% static 'sixg/images/photos/team/2.jpg' %}" alt="">
							</div>
							<div class="info">
								<strong>Lance Bogrol</strong>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-github"></i></a></li>
								</ul>
							</div>
						</div>
						<span>Visual Designer</span>
						<div class="body">
							Pellentesque lectus ante, dictum tempor dui quis, sceler semper erat aenean.
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
					<div class="team-item">
						<div class="header">
							<div class="img">
								<img src="{% static 'sixg/images/photos/team/3.jpg' %}" alt="">
							</div>
							<div class="info">
								<strong>Valent Morose</strong>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-github"></i></a></li>
								</ul>
							</div>
						</div>
						<span>Android Developer</span>
						<div class="body">
							Morbi ornare sapien a nulla condimentum porta. Praesent finibus, sapien.
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
					<div class="team-item">
						<div class="header">
							<div class="img">
								<img src="{% static 'sixg/images/photos/team/4.jpg' %}" alt="">
							</div>
							<div class="info">
								<strong>Giles Posture</strong>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-github"></i></a></li>
								</ul>
							</div>
						</div>
						<span>iOS Developer</span>
						<div class="body">
							Nam pharetra suscipit lorem, vitae efficitur dolor dapibus in. Integer maximus.
						</div>
					</div>
				</div>
			</div>{% endcomment %}
		</div>
	</section>
	<!-- ***** Our Team End ***** -->

{% endblock %}

sixg/templates/sixg/services.html
{% extends "layout/base_all.html" %}
{% load static %}

{% block content %}
<section class="page">
		<!-- ***** Page Top Start ***** -->
		<div class="cover" data-image="{% static 'sixg/images/photos/parallax.jpg' %}">
			<div class="page-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<h1>Наши услуги</h1>
						</div>
						<div class="col-lg-12 text-center">
							<ol class="breadcrumb">
								<li><a href="{% url 'sixg:index' %}">Главная</a></li>
								<li class="active">Наши услуги</li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ***** Page Top End ***** -->

		<!-- ***** Page Content Start ***** -->
		<div class="page-bottom pbottom-70">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="services-single.html" class="services-post">
							<div class="img">
								<img src="{% static 'sixg/images/photos/services/1.jpg' %}" alt="">
							</div>
							<div class="post-content">
								<div class="icon">
									<i class="fa fa-chevron-right"></i>
								</div>
								<h3>Создание сайтов</h3>
								<div class="text">
									В разработке
								</div>
							</div>
						</a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="services-single.html" class="services-post">
							<div class="img">
								<img src="{% static 'sixg/images/photos/services/2.jpg' %}" alt="">
							</div>
							<div class="post-content">
								<div class="icon">
									<i class="fa fa-chevron-right"></i>
								</div>
								<h3>Разработка приложений</h3>
								<div class="text">
									В разработке.
								</div>
							</div>
						</a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="services-single.html" class="services-post">
							<div class="img">
								<img src="{% static 'sixg/images/photos/services/3.jpg' %}" alt="">
							</div>
							<div class="post-content">
								<div class="icon">
									<i class="fa fa-chevron-right"></i>
								</div>
								<h3>Написание технического задания</h3>
								<div class="text">
									В разработке.
								</div>
							</div>
						</a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="services-single.html" class="services-post">
							<div class="img">
								<img src="{% static 'sixg/images/photos/services/4.jpg' %}" alt="">
							</div>
							<div class="post-content">
								<div class="icon">
									<i class="fa fa-chevron-right"></i>
								</div>
								<h3>Создание не типичных проектов.</h3>
								<div class="text">
									В разработке.
								</div>
							</div>
						</a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="services-single.html" class="services-post">
							<div class="img">
								<img src="{% static 'sixg/images/photos/services/5.jpg' %}" alt="">
							</div>
							<div class="post-content">
								<div class="icon">
									<i class="fa fa-chevron-right"></i>
								</div>
								<h3>Использование современных подходов и технологий</h3>
								<div class="text">
									в разработке
								</div>
							</div>
						</a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="services-single.html" class="services-post">
							<div class="img">
								<img src="{% static 'sixg/images/photos/services/6.jpg' %}" alt="">
							</div>
							<div class="post-content">
								<div class="icon">
									<i class="fa fa-chevron-right"></i>
								</div>
								<h3>Создание minicrm под нужды бизнеса</h3>
								<div class="text">
									в разработке
								</div>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<!-- ***** Page Content End ***** -->
	</section>


	<!-- ***** Parallax Start ***** -->
	<section class="parallax">
		<div class="parallax-content">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="info">
							<p>Мы разрабатываем и создаем дизайн <span>ваших проектов</span> которые помогут вам вести бизнес.</p>
							<a class="btn-white-line" href="{% url 'sixg:contact' %}">Свяжитесь с нами</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- ***** Parallax End ***** -->


	<section class="page">
		<!-- ***** Page Content Start ***** -->
		<div class="page-bottom mtop-100 pbottom-40">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="about mobile-margin-bottom-100">
							<div class="about-image">
								<img src="{% static 'sixg/images/photos/about/2.jpg' %}" alt="">
							</div>
							<div class="about-text">
								<h2>Создаем веб сервисы от начала и до конца</h2>
								<p>в разработке</p>
                            </div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ***** Page Content End ***** -->
	</section>
{% endblock %}